### ISSUE TITLE
Add Gym Website template

### ISSUE THREAD

**Issue by nouraan-ahmed** [arpit456jain/Cool-Front-End-Templates#682] opened 2022-04-23 19:53 UTC
## Issue Type:
-  Feature Request

## **Describe the project**
An interactive Gym website using HTML , CSS and javascript

**Comment by nouraan-ahmed** [comment] 2022-04-23 19:55
@VidhiBhatt01 Please assign me to this task

**Comment by VidhiBhatt01** [comment] 2022-04-25 16:46
You can not raise a PR before the issue is assigned. Be careful from next time else the PR will be marked as invalid

**Comment by DEEPIKA-SUK** [comment] 2022-05-05 18:35
@nouraan-ahmed make pr by today.

**Closed** 2022-05-08 12:28 UTC
Labels: GSSoC22
