### ISSUE TITLE
Add an E-commerce Products page template

### ISSUE THREAD

**Issue by zetabug** [arpit456jain/Cool-Front-End-Templates#180] opened 2021-10-24 19:34 UTC
Hey @arpit456jain 

I want to add an E-commerce Products page Template that I made using HTML,CSS. It is completely Responsive and looks good on all devices . 
I am contributing this as a participant for HACKTOBERFEST.

![Screenshot from 2021-10-25 01-02-26](https://user-images.githubusercontent.com/72355377/138609810-6ca74e9f-b921-42af-acdb-3d426cd5d43c.png)
![Screenshot from 2021-10-25 01-01-50](https://user-images.githubusercontent.com/72355377/138609813-4d678e2c-6fa9-4ed5-9fe8-81f9ced4bdb7.png)

**Comment by 1ananya3** [comment] 2022-02-27 14:45
Is the issue is solved otherwise I can work.Please assign to me

**Comment by rashi1405** [comment] 2022-02-27 16:40
hello , I am a participant of GSSOC'22 , can you assign me this project to work .

**Comment by shubham2-002** [comment] 2022-02-28 09:57
Hello , I am a participant of GSSOC 22 can you assign this project to me I will make completely responsive e commerce product page

**Comment by sulogna2001** [comment] 2022-02-28 18:17
Hey Can you assign me this issue for GSsoc22

**Comment by srinjoy-26** [comment] 2022-03-01 13:17
I have already raised an issue regarding this and 2-3 more templates . Please assign me.

**Closed** 2022-03-06 04:11 UTC
Labels: GSSoC22
