### ISSUE TITLE
Make a responsive Navbar for the website

### ISSUE THREAD

**Issue by Abh1shekSingh** [arpit456jain/Cool-Front-End-Templates#226] opened 2022-03-01 14:39 UTC
## Issue Type:

Adding some responsiveness to the Navbar for mobile view

## **Describe the bug**

Designing and developing responsive navbar

## **Possible solution**

Just to fix some CSS code

**Comment by Abh1shekSingh** [comment] 2022-03-01 14:39
@arpit456jain  Please assign this issue to me. I will Definetly fix in in few seconds . Please assign this issue to me

**Comment by Abh1shekSingh** [comment] 2022-03-01 16:04
Sir please assign this issue to me @arpit456jain  I know how to fix this issue. please assign this to me

**Comment by Aditya3403** [comment] 2022-03-01 16:23
Sir I would like to work on this issue. Kindly assign this issue to me.

**Comment by Abh1shekSingh** [comment] 2022-03-01 16:25
> Sir I would like to work on this issue. Kindly assign this issue to me.

Sir i have created this issue by exploring the website, this is not created by maintainer. I am already working on it, just waiting for maintainer to assign, so that i can Pull request. What you have to do is, Explore the webiste, and find the issue create the issue and wait for assignment
Thank you

**Comment by arpit456jain** [comment] 2022-03-01 18:05
> @arpit456jain Please assign this issue to me. I will Definetly fix in in few seconds . Please assign this issue to me

i guess navbar is responsive ?

can u share some ss where its not responsive

**Comment by Abh1shekSingh** [comment] 2022-03-02 03:30
This navbar is already created by me sir.. but you said make new issue and
make navbar responsive. Thats why i had created this issue again. for
making responsiveness in the navbar please assign this issue. i am done
with responsive navbar just need Pull request

**Comment by Abh1shekSingh** [comment] 2022-03-02 05:43
@arpit456jain  sir i can make it better please beleive me. i can make it more better

**Comment by VidhiBhatt01** [comment] 2022-03-02 12:39
@Abh1shekSingh the issue is assigned to you. Happy contributing!

**Closed** 2022-03-12 10:45 UTC
Labels: GSSoC22
