### ISSUE TITLE
Found covid19/index.html page is not responsive and attractive UI template too.

### ISSUE THREAD

**Issue by ragineeguptta** [arpit456jain/Cool-Front-End-Templates#234] opened 2022-03-01 19:25 UTC
## Issue Type:

- [ ✔] Bug Report
- [ ] Feature Request
- [ ] Documentaion

## **Describe the bug**
Found covid19/index.html page is not responsive like How to prevent and download buttons and attractive UI tamplate too. 

## **Possible solution**

Want to make this page responsive and attractive with use of images and styling related Covid19. And make a popup when click in how to prevent and add download link in download tab and scroller make more attractive and images also...

## **Screenshots**

![Web capture_2-3-2022_04158_127 0 0 1](https://user-images.githubusercontent.com/83906293/156234577-6fee80a1-044b-4d72-8b39-1e0c97c1f4d4.jpeg)

**Comment by sulogna2001** [comment] 2022-03-02 06:56
Hey Can I work  on  this issue under GSSOC22

**Comment by ragineeguptta** [comment] 2022-03-02 07:18
@sulogna2001 Hey I'm already working on this..
Please check another pages one by one there are lot's of issues..

**Comment by VidhiBhatt01** [comment] 2022-03-02 12:44
@ragineeguptta the issue is assigned to you. Happy Contributing!

**Comment by ragineeguptta** [comment] 2022-03-02 15:36
@VidhiBhatt01 thank you

**Closed** 2022-03-12 10:51 UTC
Labels: GSSoC22, Feature
