### ISSUE TITLE
Adding Gaming Template

### ISSUE THREAD

**Issue by itsmohitnamdeo** [arpit456jain/Cool-Front-End-Templates#528] opened 2022-03-30 04:03 UTC
Hello
I am GSSOC' 22 contributor.
I wanted to add Gaming Template in this project...

**Comment by VidhiBhatt01** [comment] 2022-04-01 10:49
@itsmohitnamdeo you should raise a PR only after the issue is assigned to you.

**Closed** 2022-04-01 18:49 UTC
Labels: GSSoC22
